{% set version = '0.8.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-paws.common
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/paws.common_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/paws.common/paws.common_{{ version }}.tar.gz
  sha256: 22d9d7b0d5a937439f5d7217d21e42d84d8536c90dc64cacd72ccf675fe0950c

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-base64enc
    - r-curl
    - r-digest
    - r-httr2
    - r-jsonlite
    - r-xml2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-base64enc
    - r-curl
    - r-digest
    - r-httr2
    - r-jsonlite
    - r-xml2

test:
  commands:
    - $R -e "library('paws.common')"           # [not win]
    - "\"%R%\" -e \"library('paws.common')\""  # [win]

about:
  home: https://github.com/paws-r/paws
  license: Apache-2.0
  summary: Functions for making low-level API requests to Amazon Web Services <https://aws.amazon.com>.
    The functions handle building, signing, and sending requests, and receiving responses.
    They are designed to help build higher-level interfaces to individual services,
    such as Simple Storage Service (S3).
  license_family: APACHE
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - conda-forge/r
    - achimgaedke

# Package: paws.common
# Type: Package
# Title: Paws Low-Level Amazon Web Services API
# Version: 0.8.1
# Authors@R: c( person("David", "Kretch", email = "david.kretch@gmail.com", role = "aut"), person("Adam", "Banker", email = "adam.banker39@gmail.com", role = "aut"), person("Dyfan", "Jones", email = "dyfan.r.jones@gmail.com", role = "cre"), person("Amazon.com, Inc.", role = "cph") )
# Description: Functions for making low-level API requests to Amazon Web Services <https://aws.amazon.com>. The functions handle building, signing, and sending requests, and receiving responses. They are designed to help build higher-level interfaces to individual services, such as Simple Storage Service (S3).
# License: Apache License (>= 2.0)
# URL: https://github.com/paws-r/paws
# BugReports: https://github.com/paws-r/paws/issues
# Encoding: UTF-8
# LinkingTo: Rcpp
# Imports: base64enc, curl, digest, httr2, jsonlite, methods, utils, stats, Rcpp, xml2
# Suggests: covr, crayon, mockery, withr, rstudioapi, testthat (>= 3.0.0)
# SystemRequirements: pandoc (>= 1.12.3) - http://pandoc.org
# RoxygenNote: 7.3.2
# Collate: 'RcppExports.R' 'util.R' 'cache.R' 'struct.R' 'handlers.R' 'iniutil.R' 'config.R' 'logging.R' 'dateutil.R' 'credential_sso.R' 'credential_sts.R' 'url.R' 'net.R' 'credential_providers.R' 'credentials.R' 'client.R' 'convert.R' 'service.R' 'custom_dynamodb.R' 'custom_rds.R' 'head_bucket.R' 'http_status.R' 'error.R' 'custom_s3.R' 'handlers_core.R' 'handlers_ec2query.R' 'handlers_jsonrpc.R' 'handlers_query.R' 'handlers_rest.R' 'handlers_restjson.R' 'tags.R' 'xmlutil.R' 'handlers_restxml.R' 'handlers_stream.R' 'idempotency.R' 'jsonutil.R' 'mock_bindings.R' 'onLoad.R' 'paginate.R' 'populate.R' 'populateutil.R' 'queryutil.R' 'request.R' 'retry.R' 'service_parameter_helper.R' 'signer_v4.R' 'signer_s3.R' 'signer_s3v4.R' 'signer_v1.R' 'signer_v2.R' 'time.R'
# Config/testthat/edition: 3
# NeedsCompilation: yes
# Packaged: 2025-02-08 17:01:09 UTC; dyfanjones
# Author: David Kretch [aut], Adam Banker [aut], Dyfan Jones [cre], Amazon.com, Inc. [cph]
# Maintainer: Dyfan Jones <dyfan.r.jones@gmail.com>
# Repository: CRAN
# Date/Publication: 2025-02-09 00:10:02 UTC
